var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                x                  xxxxxxxxxxx                   xx!xx          ",
   "                x                  xooooooooox                   x!!!x          ",
   "               xx                  xooooooooox                   xx!xx          ",
   "                x                  xooooooooox                    xvx           ",
   "                x                  xooooooooox                              xx  ",
   "  xx          xxx      xxxx        xooooooooox         xxxxxxxx              x  ",
   "  x             xxx     o x        xxxx   xxxx                            oo x  ",
   "  x             x         x                        xx                     oo x  ",
   "  x          xxxx       o x                                               oo x  ",
   "  x  @          x         x               E                      xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                             ooo                                                  ",
   "                                                 xxx                                                              ",
   "                                                 x!x          E                                                   ",
   "                                                 xvx      xxxxxxxxxxxxx                                           ",
   "                                                                                                                  ",
   "                              x                                                                                   ",
   "                              x                xx    x               x   x         x         x                    ",
   "                              xxx   xxx   x    x     x               x   x         x         x                    ",
   "                                x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "                                x   x!!!!!!!!!!x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x!!!!!!!!!!x  o  x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx   xx         x     x               x           x x oo      x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x           x x oo      x                    ",
   "!!!!x x!!!!!!x         xxxxxxxx!!!!!xxxxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x                                       xx!!!!!!xx !!!!!                xx     xx                    ",
   "!!!!x x!!!!!!x o     o            o                xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         xxxxxxxx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x   xxx   x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                   xxxxxxxxxxxxxxx               xx!xx          ",
   "                                   !!!!!!!!!!!!!!x               x!!!x          ",
   "                                   v!!!!!!!!!!!!!x               xx!xx          ",
   "                                    v!!!!!!!!!!!!x                xvx           ",
   "              xxxx                   v!!!!!!!!!!!x                          xx  ",
   "  xx              x                   x!!!!!!!!!!x     xxxxxxxx              x  ",
   "  x      x         x    o              xxxxxxxxxxx                           x  ",
   "  x                 x                              xx                        x  ",
   "  x                  x  o x                                                  x  ",
   "  x  @                x   x                      E               xxxxx oo    x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["      vvvvvvvvvvvvvvvvvvvvvvv                                                   ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  x  @     S   ooo                        E                          ooo     x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
